version: "3.3"

services:
  honeypot:
    build: .
    volumes:
        - .:/app
    environment:
      - ports=21 25 110 143 465 587 993 995 3306 8080
    ports:
        - "21:21"
        - "25:25"
        - "110:110"
        - "143:143"
        - "465:465"
        - "587:587"
        - "993:993"
        - "995:995"
        - "3306:3306"
        - "8080:8080"
    command: /app/honeypot.sh